(function($,Drupal,window,document,undefined){$(document).ready(function(){$('#block-quicktabs-ask-a-question').show('slide');});function is_touch_device(){return 'ontouchstart'in window||'onmsgesturechange'in window;};if(is_touch_device()){$(document.documentElement).addClass('touch');}})(jQuery,Drupal,this,this.document);(function($){Drupal.behaviors.sqe_view_more_view_less={attach:function(context,settings){var vmvl_link=$('a.view-more-view-less',context);vmvl_link.each(function(){var link=$(this);var extra_rows=link.closest('.view').find('> .view-content > .views-row, > .view-content .views-table > tbody > tr.views-row').slice(5);if(extra_rows.size()==0){link.hide();}else{extra_rows.hide();link.click(function(){var link=$(this);extra_rows.toggle();var oldtext=link.text();var newtext=oldtext=='View More'?'View Less':'View More';link.text(newtext);return false;});}});}}
Drupal.behaviors.modify_register_form={attach:function(context,settings){var url=window.location.pathname;if(url.indexOf('user/register')>0){var userPrompt=$('.user-prompt-summary').detach();userPrompt.insertBefore('#block-hybridauth-hybridauth');$('.hybridauth-widget-wrapper .item-list h3').text('Register With');}}}
Drupal.behaviors.hide_sponsors={attach:function(context,setting){if($('[id^="block-google-admanager-superslotsponsors-"] [id^="google_ads_div"]').length==0){$('[id^="block-google-admanager-superslotsponsors-"]').remove();}}}})(jQuery);;(function($){Drupal.behaviors.sqe_update_addthis_buttons={attach:function(context,settings){function addthis_resize_icons(){var viewport=$(window).width();var addthis=$('.addthis_toolbox');var icons=addthis.children().size();var hidden=$('.addthis_toolbox > *').filter(':hidden').size();var addthis_children=$('.addthis_toolbox').children();if(viewport<=991){if($('.addthis_toolbox .atclear').length){icons=icons-1;$('.addthis_toolbox .atclear').remove();}
var width=100/icons;addthis_children.each(function(){$(this).css("width",width+"%");})
if($('.addthis_toolbox .flag-bookmarks').length){$('.addthis_toolbox .flag-wrapper').css("position","absolute");}
if($('.flag').length){$('.flag').css("width",width+"%");}
if($('.addthis_toolbox .field-name-field-short-url').length){$('.addthis_toolbox .field-name-field-short-url').css("display","inline-block");}}
else{$('.field-name-field-short-url').css("width","52px");$('.field-name-field-short-url').css("display","block");$('.print-page').css("width","52px");$('.addthis_toolbox .flag-bookmarks .flag').css("width","52px");if($('.addthis_toolbox .flag-bookmarks').length){$('.addthis_toolbox .flag-wrapper').css("position","relative");}}}
$(window).on('resize',function(){addthis_resize_icons();});function headerpadding(){if($('.addthis_toolbox').length){$('#header, #content').attr('style','padding-left: 40px');}}
$(window).on('load',function(){$('.short-url-inline, .flag-bookmarks, .print-page').attr('style','visibility: visible !important');addthis_resize_icons();headerpadding();$("<style>").text(".flag-bookmarks { visibility: visible !important; }").appendTo("head");});}}})(jQuery);;